version: '3.9'

services:

  nginx:
    image: nginx:1.22-alpine
    container_name: camagru-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - camagru-network

  php:
    build: ./config/php
    container_name: camagru-php
    volumes:
      - ./app:/var/www/html
    networks:
      - camagru-network

  mysql:
    image: mysql:8
    container_name: camagru-mysql
    env_file:
      - .env
    volumes:
      - camagru_db:/var/lib/mysql
      - ./config/db-init:/docker-entrypoint-initdb.d
    networks:
      - camagru-network

  phpmyadmin:
    image: phpmyadmin:latest
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - camagru-network

volumes:
  camagru_db:


networks:
  camagru-network:
    driver: bridge
