version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80" # Accès à l'application via http://localhost:8000
    volumes:
      - ./src:/var/www/html # Synchroniser les fichiers locaux avec le conteneur
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
